### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/map-component#67] opened 2019-10-29 08:25 UTC
```js
Check the render method of `MapComponent`. See https://fb.me/react-warning-keys for more information.
    in ForwardRef(Leaflet(WMSTileLayer)) (at MapComponent.js:377)
    in MapComponent (at HazardLocalEffectsMap.js:29)
    in HazardLocalEffectsMap (created by Context.Consumer)
    in Route (at App.js:33)
    in Switch (at App.js:26)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:25)
    in main (at App.js:24)
    in App (at src/index.js:11)
    in div (at src/index.js:10)
```

```js
Check the render method of `LegendComponent`. See https://fb.me/react-warning-keys for more information.
    in SingleLegend (at LegendComponent.js:26)
    in LegendComponent (at MapComponent.js:513)
    in div (created by Map)
    in Map (at MapComponent.js:482)
    in div (at MapComponent.js:476)
    in MapComponent (at HazardLocalEffectsMap.js:29)
    in HazardLocalEffectsMap (created by Context.Consumer)
    in Route (at App.js:33)
    in Switch (at App.js:26)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:25)
    in main (at App.js:24)
    in App (at src/index.js:11)
    in div (at src/index.js:10)
```

**Comment by p-a-s-c-a-l** [comment] 2020-02-20 15:34
@therter if you have some spare time maybe you can have a look at this, should be easy to fix. 
Better address this now before the warning becomes an error.

**Comment by p-a-s-c-a-l** [comment] 2020-03-06 10:59
@therter any progress to report?

**Comment by therter** [comment] 2020-03-06 11:02
I cannot reproduce this warnings in any browser. Perhaps this was accidentally fixed by any update.

**Comment by p-a-s-c-a-l** [comment] 2020-03-13 06:47
![grafik](https://user-images.githubusercontent.com/1788226/76596608-e1bdbb00-64fe-11ea-8ffc-9fae6119cf81.png)

**Comment by p-a-s-c-a-l** [comment] 2020-03-13 06:49
Open [this map](https://csis.myclimateservice.eu/apps/map-component/build/GenericMap/?url=https://csis.myclimateservice.eu&resource_uuid=c14febe8-0251-4808-8970-dcfdb1255cf9) and select one of the 'Consecutive Wet Days' layers.

**Closed** 2020-04-27 07:08 UTC
Labels: BB: Map Component, bug, on-hold, wontfix
