### ISSUE TITLE
Map component doesn't set the temperature type in EMIKAT local temperature layers.

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/map-component#62] opened 2019-10-04 16:18 UTC
related to https://github.com/clarity-h2020/data-package/issues/45

EMIKAT produces three different temperature maps (and possibly also a "discomfort" map too?). I have defined separate resources for each of them, but the map is the same for all three of them. 

This is how it SHOULD look like:

Apparent temperature is the lowest. `
https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Aview.2974&bbox=4672000.0%2C1979500.0%2C4687500.0%2C1988000.0&width=768&height=421&srs=EPSG%3A3035&format=image%2Fgif&CQL_FILTER=STUDY_VARIANT%3D%27BASELINE%27%20and%20TIME_PERIOD=%27Baseline%27%20AND%20EMISSIONS_SCENARIO=%27Baseline%27%20AND%20EVENT_FREQUENCY=%27Rare%27%20AND%20SZ_ID=2846&styles=T_A`

![image](https://user-images.githubusercontent.com/2961790/66223156-10737200-e6d3-11e9-92fc-54d575a9bcad.png)

Mean radiant temperature the highest: (replace T_A with T_MRT)
![image](https://user-images.githubusercontent.com/2961790/66223191-2c771380-e6d3-11e9-9799-4ff01209f57d.png)

and the T_UTCI is in the middle

![image](https://user-images.githubusercontent.com/2961790/66223229-41ec3d80-e6d3-11e9-81cf-9a4d8a46d762.png)

At the moment, CSIS shows the same map for all three.

**Comment by p-a-s-c-a-l** [comment] 2019-10-07 08:08
@therter how is the 'styles' parameter treated? Is it removed from the request URI?

**Comment by DenoBeno** [comment] 2019-10-07 13:18
I'm still getting the same data for all three layers on https://csis.myclimateservice.eu/study/35/step/1524/view/maps

**Comment by mattia-leone** [comment] 2019-10-07 13:22
> I'm still getting the same data for all three layers on https://csis.myclimateservice.eu/study/35/step/1524/view/maps

Please reload the page and try again. Now you should see different data

**Comment by therter** [comment] 2019-10-07 13:24
> I'm still getting the same data for all three layers on https://csis.myclimateservice.eu/study/35/step/1524/view/maps

Please reload the page and try again. Now you should see different data

**Comment by therter** [comment] 2019-10-07 14:07
The layers from emikat have the following urls:
`https://service.emikat.at/geoserver/clarity/wms?CQL_FILTER=STUDY_VARIANT=%27BASELINE%27%20and%20TIME_PERIOD=%2720710101-21001231%27%20AND%20EMISSIONS_SCENARIO=%27rcp85%27%20AND%20EVENT_FREQUENCY=%27Rare%27%20AND%20SZ_ID=3189&&service=WMS&request=GetMap&layers=clarity%3Aview.2974&styles=T_UTCI%0D%0A&format=image%2Fpng&transparent=true&version=1.1.1&leaflet=%5Bobject%20Object%5D&width=1536&height=1536&srs=EPSG%3A3857&tileSize=1536&attribution=&bbox=2622095.8182946863,4539747.98391319,2680799.456017702,4598451.621636205`

`https://service.emikat.at/geoserver/clarity/wms?CQL_FILTER=STUDY_VARIANT=%27BASELINE%27%20and%20TIME_PERIOD=%2720710101-21001231%27%20AND%20EMISSIONS_SCENARIO=%27rcp85%27%20AND%20EVENT_FREQUENCY=%27Rare%27%20AND%20SZ_ID=3189&&service=WMS&request=GetMap&layers=clarity%3Aview.2974&styles=T_A%0D%0A&format=image%2Fpng&transparent=true&version=1.1.1&leaflet=%5Bobject%20Object%5D&width=1536&height=1536&srs=EPSG%3A3857&bbox=2622095.8182946863,4539747.98391319,2680799.456017702,4598451.621636205`

`https://service.emikat.at/geoserver/clarity/wms?CQL_FILTER=STUDY_VARIANT=%27BASELINE%27%20and%20TIME_PERIOD=%2720710101-21001231%27%20AND%20EMISSIONS_SCENARIO=%27rcp85%27%20AND%20EVENT_FREQUENCY=%27Rare%27%20AND%20SZ_ID=3189&&service=WMS&request=GetMap&layers=clarity%3Aview.2974&styles=T_MRT%0D%0A&format=image%2Fpng&transparent=true&version=1.1.1&leaflet=%5Bobject%20Object%5D&width=1536&height=1536&srs=EPSG%3A3857&tileSize=1536&attribution=&bbox=2622095.8182946863,4539747.98391319,2680799.456017702,4598451.621636205`


The layer from your image is the layer "Agricultural Areas in Europe". This layer comes from another wms:
`http://services.clarity-h2020.eu:8080/geoserver/clarity/ows?&service=WMS&request=GetMap&layers=clarity%3Aagricultural_areas&styles=&format=image%2Fpng&transparent=true&version=1.1.1&leaflet=%5Bobject%20Object%5D&width=1536&height=1536&srs=EPSG%3A3857&bbox=2622095.8182946863,4539747.98391319,2680799.456017702,4598451.621636205`

**Comment by humerh** [comment] 2019-10-07 14:52
I dont unterstand, I get 3 different pictures.

**Comment by therter** [comment] 2019-10-07 14:58
> I dont unterstand, I get 3 different pictures.

Before the last update of the map-component, the style parameter was ignored by the map-component. This was not a emikat problem and the problem is fixed. So I think, I can close this issue

**Closed by therter** 2019-10-07 14:58 UTC
Labels: bug
